version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    image: cushy79/rails
    build: ./rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./rails:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
